export * from './Viajes/formulario/formulario.component'
export * from './Viajes/table-view/table-view.component'
export * from './Vehiculos/table-view/table-view.component'
export * from './Ciudades/table-view/table-view.component'
export * from './Status/not-found/not-found.component'
export * from './ViewRoutes'
